Alteernlingual/urls.py
from django.contrib import admin


from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from alteernlingual_user import views
import alteernlingual_user
from django.contrib.auth import views as auth_views
import alteernlingual_subjects


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/signup/', views.register_request, name='signup'),
    path('accounts/logout/', views.logout_request, name='logout'),
    path('', include('alteernlingual_user.urls')),
    path('class/', include('Alteernlingual_topic.urls')),
    path('subjects/', include('alteernlingual_subjects.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),


    path('oauth/', include('social_django.urls', namespace='social')),  # social-auth
    path('terms-of-service/', views.termsOfService, name='termsOfService'),
    path('privacy-policy/', views.privacyPolicy, name='privacyPolicy'),
    path('partner-with-us/', views.partnerWithUS, name='partnerWithUS'),
    path('for-educators/', views.forEducators, name='forEducators'),
    path('for-business/', views.forBusiness, name='forBusiness'),
    path('careers/', views.careers, name='careers'),
    path('our-approach/', views.ourApproach, name='ourApproach'),
    path('alteernlingual-story/', views.alteernlingualStory, name='alteernlingualStory'),
    path('blog/', views.blog, name='blog'),

    #social auth
    # path('social-auth/', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alteernlingual_subjects/urls.py
from django.urls import path
from . import views

app_name = 'subject'

urlpatterns = [ 
	path('', views.subjectView.as_view(), name='subject_view'),
	 path('follow/<int:pk>', views.followSubjectView.as_view(), name='follow_subject'),
	# path('<int:pk>', views.languageDetail.as_view(), name='subjects'),
	path('topics/<int:pk>', views.subjectDetail.as_view(), name='subjects_topics'),
	path('topic-detail/<int:pk>', views.topicContentDetail.as_view(), name='topics_detail'),
]

alteernlingual_subjects/models.py
from django.db import models
from django.utils.translation import gettext as _
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.contrib.auth.models import User
from Alteernlingual_topic.models import Language



class Subject(models.Model):
    title = models.CharField(_("title"), max_length=150) 
    description = models.TextField(_("description"), max_length=255, blank=True)

    def all_user(self):
        return list(self.subject_follow.values_list('user', flat=True))

    def __str__(self):
        return self.title

class SubjectFollow(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='subject_follow',
                                 verbose_name='subject', )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class SubjectSkill(models.Model):
    title = models.CharField(max_length=60)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=True)

    def all_user(self):
        return list(self.subject_skill_follow.values_list('user', flat=True))

    def __str__(self):
        return self.title

class SubjectSkillFollow(models.Model):
    skill = models.ForeignKey(SubjectSkill, on_delete=models.CASCADE, related_name='subject_skill_follow',
                                 verbose_name='subject_skill', )
    user = models.ForeignKey(User, on_delete=models.CASCADE)



from django.urls import  reverse
class Topic(models.Model):
    title = models.CharField(_("title"), max_length=150)
    main_title =  models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_main_title = models.FileField(upload_to ='audios/', null=True, blank=True, default=None )

    subject = models.ForeignKey(Subject, verbose_name=("subject"), on_delete=models.CASCADE, default=None)
    skill = models.ForeignKey(SubjectSkill, verbose_name=("subject_skill"), on_delete=models.CASCADE, default=None)

    AR_title = models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_file_ar = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    EN_title = models.TextField(max_length=50000, null=True, blank=True, default=None,)
    audio_file_en = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    FR_title = models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_file_fr = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    HA_title = models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_file_ha = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    IG_title = models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_file_ig = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    YO_title = models.TextField(max_length=50000, null=True, blank=True, default=None)
    audio_file_yo = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    
    
    published = models.DateField(auto_now_add=True, blank=True, null=True)
    
    slug = models.SlugField(unique=True, max_length=50000, blank=True, null=True)
    read = models.ManyToManyField(User, related_name='readsubject', blank=True)
   
    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.main_title)
        return super(Topic, self).save(*args, **kwargs)

    # def get_url(self):

    #    return reverse('topic_detail', args=[self.id])

class TopicContent(models.Model):
    title = models.CharField(_("title"), max_length=150, blank=True, default=None)
    main_explanations = models.TextField(null=True, blank=True, default=None)
    audio_main = models.FileField(upload_to ='audios/', null=True, blank=True, default=None )

    subject = models.ForeignKey(Subject, verbose_name=("subject"), on_delete=models.CASCADE, default=None)
    topic = models.ForeignKey(Topic, verbose_name=("subject_topic"), on_delete=models.CASCADE, default=None)

    AR_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_ar = models.FileField(upload_to ='audios_ar/', null=True, blank=True, default=None)

    EN_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_en = models.FileField(upload_to ='audios_en/', null=True, blank=True, default=None)

    FR_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_fr = models.FileField(upload_to ='audios_fr/', null=True, blank=True, default=None)

    HA_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_ha = models.FileField(upload_to ='audios_ha/', null=True, blank=True, default=None)

    IG_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_ig = models.FileField(upload_to ='audios_ig/', null=True, blank=True, default=None)

    YO_explanations = models.TextField(null=True, blank=True, default=None)
    audio_file_yo = models.FileField(upload_to ='audios_yo/', null=True, blank=True, default=None)

    published = models.DateField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.title

alteernlingual_subjects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Alteernlingual_topic.models import Language
from .models import Subject, Topic, SubjectSkill, SubjectFollow, SubjectSkillFollow, TopicContent
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class subjectView(ListView):
    model = Subject
    context_object_name = 'subjects'
    template_name = 'subjects/listview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subjects'] = Subject.objects.all()
        context['subjectskill'] = SubjectSkill.objects.all()
        context['fsubject'] = SubjectSkill.objects.filter(subject__subject_follow__user=self.request.user)
        # context['cou'] = Topic.objects.filter(skill__skill_follow__user=self.request.user)
        # context['follow_cats'] = LanguageFollow.objects.filter(user=self.request.user)
        # context['follow_skill'] = SkillFollow.objects.filter(user=self.request.user)
        return context

class followSubjectView(TemplateView):
    template_name = 'subjects/listview.html'

    def get(self, request, *args, **kwargs):
        subject_id = kwargs['pk']
        subject = Subject.objects.filter(id=subject_id).first()
        skill_id = kwargs['pk']
        skill = SubjectSkill.objects.filter(subject_skill_follow__user=self.request.user).first()
        if subject:
            if request.GET.get('unfollow'):
                SubjectFollow.objects.filter(subject=subject, user=self.request.user).delete()
                SubjectSkillFollow.objects.filter(skill=skill, user=self.request.user).delete()
            elif SubjectFollow.objects.filter(subject__subject_follow__user=self.request.user).exists(): 
                SubjectFollow.objects.filter(subject=subject, user=self.request.user).delete()
            else:
                SubjectFollow.objects.get_or_create(subject=subject, user=self.request.user)

        return redirect(reverse('subject:subject_view'))


class followSkillView(TemplateView):
    template_name = 'subjects/listview.html'

    def get(self, request, *args, **kwargs):
        subject_id = kwargs['pk']
        subject = Subject.objects.filter(id=subject_id).first()
        skill_id = kwargs['pk']
        skill = SubjectSkill.objects.filter(subject_skill_follow__user=self.request.user).first()
        if subject:
            if request.GET.get('unfollow'):
                SubjectFollow.objects.filter(subject=subject, user=self.request.user).delete()
                SubjectSkillFollow.objects.filter(skill=skill, user=self.request.user).delete()
            elif SubjectFollow.objects.filter(subject__subject_follow__user=self.request.user).exists(): 
                SubjectFollow.objects.filter(subject=subject, user=self.request.user).delete()
            else:
                SubjectFollow.objects.get_or_create(subject=subject, user=self.request.user)

        return redirect(reverse('subject:subject_view'))


class subjectDetail(DetailView):
    model = SubjectSkill
    context_object_name = 'topic'
    template_name = 'subjects/subject_skill_detail.html'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['topics'] = Topic.objects.filter(skill=self.get_object())
        return context


class topicContentDetail(DetailView):
    model = Topic
    context_object_name = 'topictitle'
    template_name = 'subjects/subject_topic_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['topiccontent'] = TopicContent.objects.filter(topic=self.get_object())
        return context

alteernlingual_subjects/templates/subjects/listview.html
{% extends 'base.html' %}
{% block title %}Alteernlingual - Subject {% endblock %}
{% load i18n %}
{% load static %}
{% block content %}

{% include '../auth_user/userNav.html' %}
<link href=" {% static 'css/volt.css' %} " rel="stylesheet">

<style> 
.card {margin-top: 100px;}
</style>


<section id="features" class="features">
      <div class="container">
      		<div class="card border-light shadow-sm mb-4">
      <img src="{% static 'img/pencil.png' %}" alt="" height="200px" width="100%"> 

          <div class="card-body">
              <div class="table-responsive">
                 <h5><i class="fas fa-book-open"></i> &nbsp; Subjects</h5> 
                          <!-- Item -->
                          {% for subject in subjects %}
                          {% if user.id not in subject.all_user %}
                          
                              <td class="border-0"> </td>
                              <td class="border-0 font-weight-bold">
                              
											       <h5>
                                <span class="icon icon-xs icon-gray w-30">
                                      	<span class="fas fa-globe-europe"></span>
                                </span>
                              <a href="{% url 'subject:follow_subject' subject.id %}" class="btn btn-secondary">  +  <i class="fas fa-envelope"></i> {{ subject }}   </a> 
                                         {% else %} 
                               <br> <br><a style="color: red" class="btn btn-primary" href="{% url 'subject:follow_subject' subject.id %}?unfollow=true">  - <i class="fas fa-envelope-open-text"></i>   {{ subject }} </a> 	<br><br>
                            </h5>
									      		
                              </td>
                            
                         
                          {% endif %}
                            {% endfor %}
                          <!-- End of Item -->

                          <!-- End of Item -->
                      <br><hr>

                       {% for fsub in fsubject %}          
                                 <a href="{% url 'subject:subjects_topics' fsub.pk %}" class="btn btn-warning">  {{ fsub }}  </a> 
                        {% endfor %}
              </div>
          </div>
      </div>


 	  </div>
 </section><!-- End Contact Section -->


{% include '../auth_user/auth_footer.html' %}

 {% endblock %}

alteernlingual_subjects/templates/subjects/skills.html
{% extends 'base.html' %}
{% block title %}Alteernlingual - subject topcis{% endblock %}
{% load i18n %}
{% load static %}
{% block content %}

{% include '../auth_user/userNav.html' %}


<link href=" {% static 'css/volt.css' %} " rel="stylesheet">

<section id="features" class="features">
      <div class="container">
      		
<br><br><br><br>
      		<div class="card border-light shadow-sm mb-4">
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-centered table-nowrap mb-0 rounded">
                      <thead class="thead-light">
                          <tr>
                              <th class="border-0"> - </th>
                              <th class="border-0">Subjects Topics</th>
                              
                          </tr>
                      </thead>
                      <tbody>
                          <!-- Item -->
                          {% for topic in topics %}
                          <tr>
                              <td class="border-0"><a href="#" class="text-primary font-weight-bold">{{topic.id}}</a> </td>
                              <td class="border-0 font-weight-bold">
                              <span class="icon icon-xs icon-gray w-30">
                              	<span class="fas fa-globe-europe"></span>
                              </span>
									
									      			<a href="{% url 'subject:subjects_topics_detail' topic.pk %}">{{topic}}</a>
									      		
                              </td>
                            
                          </tr>
                            {% endfor %}
                          <!-- End of Item -->

                          <!-- End of Item -->
                      </tbody>
                  </table>
              </div>
          </div>
      </div>


 	  </div>
 </section><!-- End Contact Section -->


{% include '../auth_user/auth_footer.html' %}

 {% endblock %}

alteernlingual_subjects/templates/subjects/subject_skill_detail.html
{% extends 'base.html' %}
{% block title %}Alteernlingual - {{ topic.title}}{% endblock %}
{% load i18n %}
{% load static %}
{% block content %}

{% include '../auth_user/userNav.html' %}


<link href=" {% static 'css/volt.css' %} " rel="stylesheet">

<section >
    <div class="container">
      <br><br>
          <div class="card text-center">
                  <div class="card-header">
                   <i class="fas fa-book-open"></i> Select a <b> Lanuage of Interest</b>  you wish to learn
                  </div>
                  <div class="card-body">
                    <img src="{% static 'img/readcart.png' %}"  width="200px"><br>
                    <h5 class="card-title">I want to learn...</h5><br>

                         {% for topic in topics %}
                                <a  href="{% url 'subject:topics_detail' topic.pk %}"> {{ topic.title }}</a>  
                         
                        {% endfor %}
                   <br><br>
                   <!-- {% for cf in follow_cats %}
                    <i> {{ cf.language}} selected. </i> 
                      {% endfor %} -->
                    <div>
                      <i>
                        You can learn only one Language at a time
                      </i>
                    
                  </div>
                  </div>
                  
                </div>
      </div>
    </section><!-- End Contact Section -->


{% include '../auth_user/auth_footer.html' %}

 {% endblock %}

alteernlingual_subjects/templates/subjects/subject_topic_detail.html
{% extends 'base.html' %}
{% block title %}Alteernlingual - Subjects {% endblock %}
{% load i18n %}
{% load static %}
{% block content %}

{% include '../auth_user/userNavTopicDetail.html' %}


<link href=" {% static 'css/volt.css' %} " rel="stylesheet">

<section id="features" class="features">
      <div class="container">
      		
<br>
  <br>
    <br>
      <br>
      <p> Select the language you wish to be taught in below</p>
      		<br>
                  <div class="table-responsive">
  <table class="table table-striped">
  <tbody>
    <tr class="table-light"> 
      <td>
        <form name="languageAr" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ar" />
                        <a href="javascript:document.languageAr.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ar' %}
                        <i style="color: blue">Arabic</i>
                        {% else %}
                        Arabic
                        {% endif %}
                       </a>
                      </form> 
      </td>

      <td>
          <form name="languageEn" action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="en" />
                        <a href="javascript:document.languageEn.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'en' %}
                        <i style="color: blue">English</i>
                        {% else %}
                        English
                        {% endif %}
                       </a>
                      </form>
      </td>

      <td>
         <form name="languageFr" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="fr" />
                        <a href="javascript:document.languageFr.submit()">
                        {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'fr' %}
                        <i style="color: blue">Francais</i>
                        {% else %}
                        Francais
                        {% endif %}
                      </a>
                      </form> 
      </td>

       <td>
         <form name="languageHa" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ha" />
                        <a href="javascript:document.languageHa.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ha' %}
                        <i style="color: blue">Hausa</i>
                        {% else %}
                        Hausa
                        {% endif %}
                       </a>
                      </form> 
       </td>

      <td>
         <form name="languageIg" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ig" />
                        <a href="javascript:document.languageIg.submit()"> 
                      {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ig' %}
                        <i style="color: blue">Igbo</i>
                        {% else %}
                        Igbo
                        {% endif %}
                      </a>
                      </form>   

      </td>

      <td>
        <form name="languageYo" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="yo" />
                        <a href="javascript:document.languageYo.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'yo' %}
                        <i style="color: blue">Yoruba</i>
                        {% else %}
                        Yoruba
                        {% endif %}
                       </a>
                      </form> 
      </td>

    </tr>
  </tbody>
</table>
</div>
            </h6>
        <br><br>
        <h3>
        {% get_current_language as LANGUAGE_CODE %}
          {% if LANGUAGE_CODE == 'en' %}
          {{ topictitle.EN_title}}
          {% endif %}
          
          {% if LANGUAGE_CODE == 'ig' %}
          {{ topictitle.IG_title}}
          {% endif %}

          {% if LANGUAGE_CODE == 'ha' %}
          {{ topictitle.HA_title}}
          {% endif %}

           {% if LANGUAGE_CODE == 'yo' %}
          {{ topictitle.YO_title}}
          {% endif %}

           {% if LANGUAGE_CODE == 'fr' %}
          {{ topictitle.FR_title}}
          {% endif %}

          {% if LANGUAGE_CODE == 'ar' %}
          {{ topictitle.AR_title}}
          {% endif %}
          </h3>


          <br><hr>
           <p>{% for tc in topiccontent%}
        {% get_current_language as LANGUAGE_CODE %}
          {% if LANGUAGE_CODE == 'en' %}
          {{ tc.EN_explanations }}
          {% endif %}
          
          {% if LANGUAGE_CODE == 'ig' %}
          {{ tc.IG_explanations}}
          {% endif %}

          {% if LANGUAGE_CODE == 'ha' %}
          {{ tc.HA_explanations}}
          {% endif %}

           {% if LANGUAGE_CODE == 'yo' %}
          {{ tc.YO_explanations}}
          {% endif %}

           {% if LANGUAGE_CODE == 'fr' %}
          {{ tc.FR_explanations}}
          {% endif %}

          {% if LANGUAGE_CODE == 'ar' %}
          {{ tc.AR_explanations}}
          {% endif %}
          {% endfor %}
          </p>
 	  </div>
 </section><!-- End Contact Section -->


{% include '../auth_user/auth_footer.html' %}

 {% endblock %}

alteernlingual_subjects/templates/subjects/subject_topic_list.html
{% extends 'base.html' %}
{% block title %}Alteernlingual - subject topcis{% endblock %}
{% load i18n %}
{% load static %}
{% block content %}

{% include '../auth_user/userNav.html' %}


<link href=" {% static 'css/volt.css' %} " rel="stylesheet">

<section id="features" class="features">
      <div class="container">
      		
<br><br><br><br>
      		<div class="card border-light shadow-sm mb-4">
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-centered table-nowrap mb-0 rounded">
                      <thead class="thead-light">
                          <tr>
                              <th class="border-0"> - </th>
                              <th class="border-0">Subjects Topics</th>
                              
                          </tr>
                      </thead>
                      <tbody>
                          <!-- Item -->
                          {% for topic in topics %}
                          <tr>
                              <td class="border-0"><a href="#" class="text-primary font-weight-bold">{{topic.id}}</a> </td>
                              <td class="border-0 font-weight-bold">
                              <span class="icon icon-xs icon-gray w-30">
                              	<span class="fas fa-globe-europe"></span>
                              </span>
									
									      			<a href="{% url 'subject:subjects_topics_detail' topic.pk %}">{{topic}}</a>
									      		
                              </td>
                            
                          </tr>
                            {% endfor %}
                          <!-- End of Item -->

                          <!-- End of Item -->
                      </tbody>
                  </table>
              </div>
          </div>
      </div>


 	  </div>
 </section><!-- End Contact Section -->


{% include '../auth_user/auth_footer.html' %}

 {% endblock %}