Alteernlingual/urls.py
from django.contrib import admin


from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from alteernlingual_user import views
import alteernlingual_user
from django.contrib.auth import views as auth_views
import alteernlingual_subjects


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/signup/', views.register_request, name='signup'),
    path('accounts/logout/', views.logout_request, name='logout'),
    path('', include('alteernlingual_user.urls')),
    path('class/', include('Alteernlingual_topic.urls')),
    path('subjects/', include('alteernlingual_subjects.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),


    path('oauth/', include('social_django.urls', namespace='social')),  # social-auth
    path('terms-of-service/', views.termsOfService, name='termsOfService'),
    path('privacy-policy/', views.privacyPolicy, name='privacyPolicy'),
    path('partner-with-us/', views.partnerWithUS, name='partnerWithUS'),
    path('for-educators/', views.forEducators, name='forEducators'),
    path('for-business/', views.forBusiness, name='forBusiness'),
    path('careers/', views.careers, name='careers'),
    path('our-approach/', views.ourApproach, name='ourApproach'),
    path('alteernlingual-story/', views.alteernlingualStory, name='alteernlingualStory'),
    path('blog/', views.blog, name='blog'),

    #social auth
    # path('social-auth/', include('social_django.urls', namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alteernlingual_subjects/urls.py
from django.urls import path
from . import views

app_name = 'subject'

urlpatterns = [ 
	path('', views.subjectView.as_view(), name='subject_view'),
	 path('follow/<int:pk>', views.followSubjectView.as_view(), name='follow_subject'),
	# path('<int:pk>', views.languageDetail.as_view(), name='subjects'),
	path('topics/<int:pk>', views.subjectDetail.as_view(), name='subjects_topics'),
	path('topic-detail/<int:pk>', views.topicContentDetail.as_view(), name='topics_detail'),
]

alteernlingual_user/urls.py
from django.urls import path
from alteernlingual_user import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/dashboard', views.dashboard, name='dashboard'),
    path('accounts/profile', views.ProfileView.as_view(), name='profile'),
    path('accounts/change-password/', views.changePassword, name='passwordChange'),
  
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view
    	(template_name="auth_user/password_reset_form.html",
    	 email_template_name="auth_user/password_reset_email.html",
    	 subject_template_name="auth_user/password_reset_subject.txt"), name='password_reset'),

    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view
    	(template_name="auth_user/password_reset_done.html"), name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view
    	(template_name="auth_user/password_reset_confirm.html"), name='password_reset_confirm'),

    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view
    	(template_name="auth_user/password_reset_complete.html"), name='password_reset_complete'),

]

alteernlingual_user/models.py
from re import T
from django.db import models

from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.templatetags.static import static
# Create your models here.

class Profile(models.Model):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
    ]

  
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE, null=True)
    avatar = models.ImageField(upload_to="profiles/avatars/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
   
    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    @property
    def get_avatar(self):
        return self.avatar.url if self.avatar else static('img/user-thumb-lg.png')

alteernlingual_user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.


from .models import Profile


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField()

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']


def form_validation_error(form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg += "%s: %s \\n" % (field.label if hasattr(field, 'label') else 'Error', error)
    return msg

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

# class NewUserForm(UserCreationForm):
# 	email = forms.EmailField(required=True)

# 	class Meta:
# 		model = User
# 		fields = ("username", "email", "password1", "password2")

# 	def save(self, commit=True):
# 		user = super(NewUserForm, self).save(commit=False)
# 		user.email = self.cleaned_data['email']
# 		if commit:
# 			user.save()
# 		return user

alteernlingual_user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
# from alteernlingual_user.forms import SignUpForm
from django.contrib.auth.models import Group
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
# from .forms import  UserForm, ProfileForm
from django.contrib import messages
from .forms import SignUpForm

from django.utils.decorators import method_decorator
from django.views import View

from .forms import ProfileForm, form_validation_error
from .models import Profile
from Alteernlingual_topic.models import Topic, LanguageFollow, Language, LanguageLevel
from alteernlingual_subjects.models import SubjectFollow
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template

def home(request):
        return render(request, 'index.html')

def topicPercent(read_count, total_topic):
    if total_topic == 0:
        total_topic = 1
    percentage = int(read_count / total_topic * 100)

    return percentage

@login_required
def dashboard(request):
    language_follow = LanguageFollow.objects.filter(user=request.user)
    read = LanguageFollow.objects.filter(user=request.user)
    read_count = Topic.objects.filter(read=request.user, language__language_follow__user=request.user).count()
    total_topic = Topic.objects.filter(language__language_follow__user=request.user).count()
    percent =  topicPercent(read_count, total_topic)
    subject_follow = SubjectFollow.objects.filter(user=request.user)
    last_read = Topic.objects.filter(read=request.user).last()

    return render(request, 'auth_user/userDashboard.html',  {
    "read_count": read_count, "total_topic": total_topic, 'language_follow': language_follow, "percent": percent,
    "subject_follow": subject_follow, "last_read": last_read

        })


def register_request(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            email = form.cleaned_data.get('email')
            htmly = get_template('registration/email.html')
            d = { 'username': username }
            subject, from_email, to = 'welcome', 'a.damilare2012@gmail.com', email
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            user = authenticate(username=username, password=raw_password)
            user = form.save()
            login(request, user)

            msg = 'User created - please <a href="/accounts/login">login</a>.'
            success = True

            return redirect("profile")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "registration/signup.html", {"form": form, "msg": msg, "success": success})

def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("home")


@method_decorator(login_required(login_url='login'), name='dispatch')
class ProfileView(View):
    profile = None

    def dispatch(self, request, *args, **kwargs):
        self.profile, __ = Profile.objects.get_or_create(user=request.user)
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {'profile': self.profile, 'segment': 'profile'}
        return render(request, 'auth_user/userProfile.html', context)

    def post(self, request):
        form = ProfileForm(request.POST, request.FILES, instance=self.profile)

        if form.is_valid():
            profile = form.save()
            profile.user.first_name = form.cleaned_data.get('first_name')
            profile.user.last_name = form.cleaned_data.get('last_name')
            profile.user.email = form.cleaned_data.get('email')
            profile.user.save()

            messages.success(request, 'Profile saved successfully')
        else:
            messages.error(request, form_validation_error(form))
        return redirect('profile')


@login_required
def changePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('changePassword')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'auth_user/passwordChange.html', {
        'form': form
    })



def resetPassword(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password reset link has been sent to your email')
            return redirect('changePassword')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'auth_user/password_reset_form.html', {
        'form': form
    })


def termsOfService(request):
    return render(request, 'termsOfService.html')

def privacyPolicy(request):
    return render(request, 'privacyPolicy.html')

def partnerWithUS(request):
    return render(request, 'partnerWithUS.html')

def forEducators(request):
    return render(request, 'forEducators.html')

def forBusiness(request):
    return render(request, 'forBusiness.html')

def careers(request):
    return render(request, 'careers.html')

def ourApproach(request):
    return render(request, 'ourApproach.html')

def alteernlingualStory(request):
    return render(request, 'alteernlingualStory.html')

def blog(request):
    return render(request, 'blog.html')

alteernlingual_user/templates/auth_user/auth_footer.html
{% load i18n %}
 <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="container py-4">
      <div class="copyright">
        <!-- &copy; Copyright <strong><span>Alteɘrnligual</span></strong>. All Rights Reserved -->
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-app-landing-page-template/ -->
        <!-- Designed by <a href="https://thecorporatenerds.com/">The Corporate Nerds</a> -->
      </div>
    </div>
  </footer><!-- End Footer -->

alteernlingual_user/templates/auth_user/passwordChange.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

{% include './userNav.html' %}
<link href=" {% static 'css/volt.css' %} " rel="stylesheet">


<section id="faq" class="faq section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">

          <h2></h2>
          
        </div>

        <div class="accordion-list">
          

       <div class="container">
                <div class="row justify-content-center form-bg-image">
                    
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <h1 class="h3 mb-4">Reset password</h1>
                           
                            <form method="post"> 
                                 {% csrf_token %}
                                <!-- Form -->
                                  <input type="hidden" name="next" value="{{ next }}">
                                <div class="mb-4">
                                    <label for="password">Old Password</label>
                                    <div class="input-group">
                                        
                                        {{ form.old_password }}
                                        {{ form.old_password.errors }}
                                    </div>  
                                </div>                                <!-- End of Form -->
                                <!-- Form -->
                                <div class="mb-4">
                                    <label for="password">New Password</label>
                                    <div class="input-group">
                                       
                                        {{ form.new_password1 }}
                                        {{ form.new_password1.errors }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <!-- Form -->
                                <div class="mb-4">
                                    <label for="confirm_password">Confirm New Password</label>
                                    <div class="input-group">
                                       
                                            {{ form.new_password2 }}
                                            {{ form.new_password2.errors }}   
                                    </div>  
                                </div>
                                <!-- End of Form -->
                               <button class="btn btn-dark btn-lg btn-block" type="submit">Change Password</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->
{% include './auth_footer.html' %}

{% endblock %}

alteernlingual_user/templates/auth_user/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


<header id="header" class="fixed-top  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <!--<h1><a href="index.html">Alteernlingual</a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="{% url 'home' %}"><img src="{% static 'img/s.jpg' %}" alt="" class="img-fluid"></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
         

          <li><a class="nav-link scrollto" href=""></a></li>
             <li class="dropdown" id="language-switcher">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="/" />

                    <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="language" style="width: auto;" onchange="this.form.submit()">
                      {% get_current_language as LANGUAGE_CODE %}
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as languages %}
                      {% for language in languages %}

                          <option 
                            value="{{ language.code }}"
                            {% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}
                            data-content='<img src="/static/img/flags/{{ language.code }}.png">
                            <span style="display:inline-block; width:100px; padding-left: 10px; text-shadow:none">
                              {{ language.name_local }}
                              <!-- span style="color:#999;">&nbsp;[{{ language.code }}]</span -->
                            </span>'>
                            {{ language.name_local }} {{ language.code }}
                          </option>

                      {% endfor %}
                    </select>
                </form>
    </li>
        </ul>
<i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
<section id="faq" class="faq section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">

          <h2></h2>
          
        </div>

        <div class="accordion-list">
          

       <div class="container">
                <div class="row justify-content-center form-bg-image">
                   
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                   <p> Your password has been set. You may go ahead to  <a href="{% url 'login' %}">sign in</a> </p>

                        </div>
                    </div>
                </div>
            </div>



        </div>

      </div>
    </section>
{% endblock %}

alteernlingual_user/templates/auth_user/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

alteernlingual_user/templates/auth_user/userNav.html
{% load static %}
{% load i18n %}
<!-- ======= Header ======= -->
  <header id="header" class="fixed-top  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <!--<h1><a href="index.html">Alteernlingual</a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="{% url 'home' %}"><img src="{% static 'img/s.jpg' %}" alt="" class="img-fluid"></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>  <li><a href="{% url 'profile' %}"><img src="{{ user.profile.get_avatar }}"
                                         class=" rounded-circle "
                                         width="30px" height="30px"></a></li>
         <!--  <li><a class="getstarted scrollto" href="{% url 'profile' %}">{{ user.username }}</a></li> -->

          <li class="dropdown"><a href="{% url 'profile' %}"><span>{{ user.username }}</span> <i class="bi bi-chevron-down"></i></a>
          
            <ul>
              <li><a href="{% url 'passwordChange' %}">{% trans "Change password" %}</a></li>
            </ul>
          </li>

    </li>
          <li><a class="nav-link scrollto" href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a></li>
          <li><a class="nav-link scrollto" href="{% url 'lessons' %}#skill">{% trans "Lessons" %}</a></li>
          
          <li><a class="nav-link scrollto" href="{% url 'subject:subject_view' %}">{% trans "Subjects" %} </a></li>
          <li><a class="nav-link scrollto" href="{% url 'search' %}">  <i class="fas fa-search"></i> &nbsp; &nbsp;</a></li>
          
          {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'logout' %}">
            <i class="fas fa-sign-out-alt"></i> &nbsp;{% trans "Logout" %}</a></li>
                {% endif %}

        </ul>
        
        

<i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
    <div class="table-responsive">
  <table class="table table-striped">
  <tbody>
    <tr class="table-light"> 
      <td>
        <form name="languageAr" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ar" />
                        <a href="javascript:document.languageAr.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ar' %}
                        <i style="color: blue">Arabic</i>
                        {% else %}
                        Arabic
                        {% endif %}
                       </a>
                      </form> 
      </td>

      <td>
          <form name="languageEn" action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="en" />
                        <a href="javascript:document.languageEn.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'en' %}
                        <i style="color: blue">English</i>
                        {% else %}
                        English
                        {% endif %}
                       </a>
                      </form>
      </td>

      <td>
         <form name="languageFr" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="fr" />
                        <a href="javascript:document.languageFr.submit()">
                        {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'fr' %}
                        <i style="color: blue">Francais</i>
                        {% else %}
                        Francais
                        {% endif %}
                      </a>
                      </form> 
      </td>

       <td>
         <form name="languageHa" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ha" />
                        <a href="javascript:document.languageHa.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ha' %}
                        <i style="color: blue">Hausa</i>
                        {% else %}
                        Hausa
                        {% endif %}
                       </a>
                      </form> 
       </td>

      <td>
         <form name="languageIg" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="ig" />
                        <a href="javascript:document.languageIg.submit()"> 
                      {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'ig' %}
                        <i style="color: blue">Igbo</i>
                        {% else %}
                        Igbo
                        {% endif %}
                      </a>
                      </form>   

      </td>

      <td>
        <form name="languageYo" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                     <input name="next" type="hidden" value="{{ redirect_to }}" />
                        <input name="language" type="hidden" value="yo" />
                        <a href="javascript:document.languageYo.submit()">
                         {% get_current_language as LANGUAGE_CODE %} 
                        {% if LANGUAGE_CODE == 'yo' %}
                        <i style="color: blue">Yoruba</i>
                        {% else %}
                        Yoruba
                        {% endif %}
                       </a>
                      </form> 
      </td>

    </tr>
  </tbody>
</table>
</div>
  </header><!-- End Header -->

 

alteernlingual_user/templates/auth_user/userNavTopicDetail.html
{% load static %}
{% load i18n %}
<!-- ======= Header ======= -->
  <header id="header" class="fixed-top  header-transparent ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <!--<h1><a href="index.html">Alteernlingual</a></h1>-->
        <!-- Uncomment below if you prefer to use an image logo -->
         <a href="{% url 'home' %}"><img src="{% static 'img/s.jpg' %}" alt="" class="img-fluid"></a>
      </div>

      <nav id="navbar" class="navbar">
        <ul>  <li><a href="{% url 'profile' %}"><img src="{{ user.profile.get_avatar }}"
                                         class=" rounded-circle "
                                         alt="Profile-avatar" width="30px" height="30px"></a></li>
         <!--  <li><a class="getstarted scrollto" href="{% url 'profile' %}">{{ user.username }}</a></li> -->

          <li class="dropdown"><a href="{% url 'profile' %}"><span>{{ user.username }}</span> <i class="bi bi-chevron-down"></i></a>
          
            <ul>
              <li><a href="{% url 'passwordChange' %}">{% trans "Change password" %}</a></li>
            </ul>
          </li>

    </li>
          <li><a class="nav-link scrollto" href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a></li>
          <li><a class="nav-link scrollto" href="{% url 'lessons' %}">{% trans "Lessons" %}</a></li>
          <li><a class="nav-link scrollto" href="{% url 'subject:subject_view' %}">{% trans "Subjects" %}</a></li>
          
          <li><a class="nav-link scrollto" href="{% url 'search' %}">  <i class="fas fa-search"></i>&nbsp;&nbsp;</a></li>
          
          {% if user.is_authenticated %}
          <li><a class="nav-link scrollto" href="{% url 'logout' %}">
            <i class="fas fa-sign-out-alt"></i>&nbsp; {% trans "Logout" %}</a></li>
                {% endif %}

        </ul>
        
        

<i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
   
  </header><!-- End Header -->

 